# https://taskfile.dev

version: '3'

tasks:
  up:
    cmds:
      - docker-compose -f docker/docker-compose.yml up -d
  build:
    cmds:
      - docker-compose -f docker/docker-compose.yml build
  down:
    cmds:
      - docker-compose -f docker/docker-compose.yml down
